name: Test Builds

on:
  schedule:
    - cron: "0 0 */2 * *"

concurrency:
  group: Test Builds-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        macos-version: [macos-14]

    runs-on: ${{ matrix.macos-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter app
        run: flutter build macos --release --tree-shake-icons

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: alter-darwin-arm64
          path: build/macos/Build/Products/Release/alter.app
          retention-days: 2
