name: Test Builds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *"

concurrency:
  group: Test Builds-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        macos-version: [macos-14]

    runs-on: ${{ matrix.macos-version }}

    env:
      FILE_NAME: alter-pre-darwin-arm64.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter app
        run: |
          flutter build macos --release --tree-shake-icons
          zip -r ${{ env.FILE_NAME }} build/macos/Build/Products/Release/alter.app

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.FILE_NAME }}
          retention-days: 2
