name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        macos-version: [macos-13, macos-14, macos-15]

    runs-on: ${{ matrix.macos-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter app
        run: flutter build macos --tree-shake-icons

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/macos/Build/Products/Debug/alter.app
          retention-days: 1
